-- 008_ai_generated_cv_flag.sql
-- Add ai_generated flag to screen CVs that may have been generated by AI

-- Candidates table (main CV/candidate records)
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN DEFAULT FALSE;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS ai_generated_confidence DECIMAL(3,2); -- 0.00-1.00, nullable
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS ai_generated_checked_at TIMESTAMPTZ;

-- Index for filtering flagged CVs
CREATE INDEX IF NOT EXISTS idx_candidates_ai_generated ON candidates(ai_generated) WHERE ai_generated = TRUE;
